message_templates = {
    'en': {
        "start": "Hey there! I'm your friendly GPT assistant. Just type /help or jump right in using commands menu!",
        "ask": "Need answers? Just type your question after /ask. For example: /ask What are the health benefits of green tea?",
        "image_prompt": "Looking for an image? Describe it after /image. Try something like: /image A serene mountain landscape.",
        "audio_prompt": "Want to hear something? Type your text after /audio. For instance, /audio I am robot",
        "audio_error": "Oops! There was a hiccup with creating audio.",
        "image_error": "Oops! Something went wrong with the image generation.",
        "network_error": "Network hiccup detected. Please check your connection and try again.",
        "request_error": "Oops! There was a snag in your request. It might contain text our safety system doesn't allow.",
        "limit_error": "You've hit a limit. Take a break and try again in a minute!",
        "client_error": "Hmm, there seems to be a glitch on your end. Please double-check your request and try again.",
        "auth_error": "Authentication issue detected. Please try again later.",
        "server_error": "Server-side hiccup! Please retry in a bit.",
        "help": "Need assistance? Use commands like /ask, /language, /image, /audio, and /help to interact with me.",
        "language_confirmation": "Language set to English. Ready to go!",
        "language_selection": "Choose from 2 languages:",
        "processing": "Hang tight! We're processing your request.",
        "error": "Uh-oh! We ran into an unexpected issue while processing. Try again later.",
        "ask_limit_reached": "Daily limit reached for /ask. Time for a break!",
        "image_limit_reached": "You've reached today's limit for /image. Try again tomorrow!",
        "audio_limit_reached": "Maximum /audio requests reached for today. More audio fun awaits tomorrow!"
    },
    'ua': {
        "start": "Привіт! Я твій GPT помічник. Просто напиши /help або відкрий меню команд!",
        "ask": "Шукаєш відповіді? Напиши своє запитання після /ask. Наприклад: /ask Як зварити пельмені?",
        "image_prompt": "Потрібне зображення? Опиши його після /image. Спробуй так: /image Пельмені.",
        "audio_prompt": "Хочеш щось почути? Введи текст після /audio. Наприклад, /audio Я робот, а ти?.",
        "audio_error": "Ой! Щось пішло не так під час створення аудіо.",
        "image_error": "Упс! Сталася помилка при генерації зображення.",
        "network_error": "Проблеми з мережею. Будь ласка, перевірте з'єднання та спробуйте знову.",
        "request_error": "Ой! Виникла проблема з вашим запитом. Можливо, він містить текст, який не допускає наша система безпеки.",
        "limit_error": "Дуже багато запитів. Спробуйте через хвилину.",
        "client_error": "Здається, проблема на вашому боці. Будь ласка, перевірте ваш запит та спробуйте ще раз.",
        "auth_error": "Проблема з аутентифікацією. Спробуйте пізніше.",
        "server_error": "Сталася помилка на сервері.",
        "help": "Використовуй команди /ask, /language, /image, /audio та /help для взаємодії.",
        "language_confirmation": "Мова встановлена на Українську.",
        "language_selection": "Виберіть з 2 мов:",
        "processing": "Тримайтеся! Ми обробляємо ваш запит.",
        "error": "Упс! Ми натрапили на неочікувану проблему під час обробки. Спробуйте ще раз",
        "ask_limit_reached": "Досягнуто щоденного ліміту для /ask. Час на перерву!",
        "image_limit_reached": "Ви вичерпали сьогоднішній ліміт для /image. Спробуйте завтра!",
        "audio_limit_reached": "Ви досягли максимальної кількості запитів /audio на сьогодні. Більше аудіо завтра!"
    }
}